# Generated by Django 4.1.7 on 2023-03-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='access_level',
            field=models.IntegerField(choices=[('Папочка', '1'), ('Раб', '2')], max_length=20, verbose_name='Уровень доступа'),
        ),
    ]
