# Generated by Django 4.1.3 on 2023-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_position_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_aes',
            field=models.CharField(max_length=100, null=True, verbose_name='Key Aes'),
        ),
    ]
