# Generated by Django 4.1.7 on 2023-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_position_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Главный'), (2, 'Не главный')], verbose_name='Уровень доступа'),
        ),
    ]
