# Generated by Django 4.1.7 on 2023-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20211016_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='type_msg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
