# Generated by Django 4.1.3 on 2023-03-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20211016_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='file_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.filemessage'),
        ),
    ]
