# Generated by Django 4.1.3 on 2023-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_filemessage_chatmodel_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='file_id',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='type_msg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
