# Generated by Django 4.1.3 on 2023-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chatmodel_file_id_chatmodel_type_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemessage',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
